# Anthos:
# Modified version taken from https://github.com/detlearsom/DetGen/tree/main

version: '3'

services:
  rsyslog:
    image: detlearsom/rsyslog
    hostname: rsyslog
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - $PWD/rsyslog.conf:/etc/rsyslog.conf
      - $PWD/logs:/var/log/rsyslog
    cap_add:
      - SYSLOG
    networks:
      - capture

  nginx:
    image: detlearsom/nginx
    hostname: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - capture
    depends_on:
      - rsyslog
    
  tcpdump_nginx:
    image: 'detlearsom/tcpdump'
    command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/dump-020-nginx-server-${CAPTURETIME}-$REPNUM.pcap"
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:nginx"
    depends_on:
      - nginx

  siege:
    image: 'detlearsom/siege'
    command: tail -f /dev/null #-c${CONCURRENT_THREADS} -r${REQUESTS} -v http://nginx
    networks:
      - capture
    depends_on:
      - tcpdump_nginx

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: "default"


