# Anthos:
# Modified from https://github.com/detlearsom/DetGen/tree/main

version: '3'

services:
  rsyslog:
    image: detlearsom/rsyslog
    hostname: rsyslog
    container_name: rsyslog
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - $PWD/rsyslog.conf:/etc/rsyslog.conf
      - $PWD/logs:/var/log/rsyslog
    cap_add:
      - SYSLOG
    networks:
      - capture

  nginx:
    image: detlearsom/nginx
    hostname: nginx
    volumes:
      - '$PWD/logs:/var/log/nginx'
      - '$PWD/nginx.conf:/etc/nginx/nginx.conf'
      - '$PWD/conf:/usr/share/nginx/html'
    ports:
      - 80:80
      - 443:443
    networks:
      - capture
    depends_on:
      - rsyslog


  wget:
    image: 'detlearsom/wget'
    command: tail -f /dev/null #sh -c "sleep 0.1 && wget --recursive --page-requisites --html-extension --convert-links "http://nginx" -P /data"
    volumes:
      - "$PWD/data:/data"
    networks:
      - capture
    depends_on:
      - tcpdump_nginx

  tcpdump_nginx:
    image: 'detlearsom/tcpdump'
    command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/dump-021-nginx-server-${CAPTURETIME}-$REPNUM.pcap"
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:nginx"
    depends_on:
      - nginx

networks:
  capture:
    driver: "bridge"
