# Anthos:
# Modified from https://github.com/glo-fi/DetGen/tree/master

version: '2'
services:

  rsyslog:
    image: detlearsom/rsyslog
    hostname: rsyslog
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - $PWD/rsyslog.conf:/etc/rsyslog.conf
      - $PWD/logs:/var/log/rsyslog
    cap_add:
      - SYSLOG
    networks:
      capture:
        ipv4_address: 172.26.0.3

  nginx:
    image: 'detlearsom/nginx'
    hostname: nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - $PWD/conf:/etc/nginx/conf.d:ro
      - $PWD/index:/usr/share/nginx/html
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/logs:/var/log/nginx
    networks:
      capture:
        ipv4_address: 172.26.0.2
    depends_on:
      - rsyslog

  tcpdump_nginx:
    image: 'detlearsom/tcpdump'
    command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/dump-110-vuln-nginx-server-${CAPTURETIME}-$REPNUM.pcap"
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:nginx"
    depends_on:
      - nginx

  b_forcer:
    image: 'detlearsom/docker-python-requests'
    volumes:
      - $PWD/b_forcer_share:/var/lib/
    command: tail -f /dev/null # python /var/lib/brute_force.py
#    command: sleep 1000
    networks:
      - capture
    depends_on:
      - tcpdump_nginx

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24
          gateway: 172.26.0.1


